
# spin-up server
up:
	python src/manage.py runserver

# create python migrations file
make-migrations:
	python src/manage.py makemigrations

# commit the migrations to the DB
migrate:
	python src/manage.py migrate